### ISSUE TITLE
请问大佬用dp口输出4k屏幕会有闪屏黑屏现象吗？

### ISSUE THREAD

**Issue by kksxsyj** [rennai/Hackintosh-10900ES-B460M-MORTAR#1]
跟大佬一样的板U，也是用的核显，不知道为啥使用过程中会有闪屏黑屏的现象？

**Comment by rennai** [comment]
我的没问题，建议你换一条dp线，注意要1.3版本及以上的，质量也要靠谱

**Comment by yaohl0911** [comment]
我是相同主板，相同bios配置，CPU是10700k，DP接口也是黑屏，重新插拔后亮几秒还是黑屏，HDMI接口没问题，Windows用DP也没问题。请问你的问题解决了吗？我查了下，到现在还没找到解决方案

**Comment by yaohl0911** [comment]
摸鱼的时候远景找了个解决方案，回家试试。先分享出来：https://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1888252&highlight=DP%2B%BA%DA%C6%C1

**Comment by yaohl0911** [comment]
DP协议切换到1.1完美解决

**Comment by kksxsyj** [comment]
> 

我是重装之后就没这种问题了
