### ISSUE TITLE
AppleALC和AppleALCU的选择

### ISSUE THREAD

**Issue by yaohl0911** [rennai/Hackintosh-10900ES-B460M-MORTAR#3]
"AppleALCU.kext is a pared down version of AppleALC that only supports digital audio - but you can still use AppleALC.kext on digital audio-only systems"
B460迫击炮非wifi版用这个EFI，音频插孔都没有用，看了下OpenCore Install Guide，有以上的描述，请问当初选择AppleALCU的原因是什么

**Comment by rennai** [comment]
我最近一直用的是蓝牙耳机，所以这次升级没测试有线耳机。刚看了一下，确实配置有问题。声卡没识别，等下有空了我在改一下EFI
