### ISSUE TITLE
睡眠时间

### ISSUE THREAD

**Issue by jackyzonewen** [rennai/Hackintosh-10900ES-B460M-MORTAR#4]
您好~请问一下你的版本从点击开始睡眠到断电后，需要多长时间？我的好像要一二十秒左右~感觉好慢

**Comment by rennai** [comment]
没注意算过，应该几秒就睡了。我这挺快的

**Comment by aboutst** [comment]
大佬您好，我是同款b460m迫击炮，同款无线网卡94360cs，想咨询一下，WiFi和蓝牙都是正常，双向隔空正常，但是handoff只能单向传输剪切板，请问遇到过这个问题吗？谢谢。
