### ISSUE TITLE
只能单向handoff

### ISSUE THREAD

**Issue by aboutst** [rennai/Hackintosh-10900ES-B460M-MORTAR#5]
大佬您好，我是同款b460m迫击炮，同款无线网卡94360cs，想咨询一下，WiFi和蓝牙都是正常，双向隔空正常，但是handoff只能单向传输剪切板，请问遇到过这个问题吗？谢谢。

**Comment by rennai** [comment]
这个应该是通病吧，我的手机和M1、黑苹果都出现过无法传输粘贴板的时候，我一般都是把两边的蓝牙和wifi都关闭再重新打开就好了。
