### ISSUE TITLE
睡眠唤醒后，蓝牙和wifi不能用的问题怎么解决

### ISSUE THREAD

**Issue by yangbe** [rennai/Hackintosh-10900ES-B460M-MORTAR#6]

**Comment by rennai** [comment]
我放弃了，实验过各种办法。一直没解决，目前是短时间休眠还没问题，时间一长再唤醒 wifi和蓝牙就不能用了。只能用usb鼠标去重新打开或关闭一下网络才能用。

应该是主板bios的问题，微星迫击炮这个板子的通病

**Comment by yangbe** [comment]
> 

我的是技嘉Z370NWiFi，直接回到BigSur了
